# features for collabritve filtering 

In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [52]:
d1 = pd.read_csv("~/Desktop/Contact.csv")

In [4]:
X = d1.iloc[:,3:-1].values
y = d1.iloc[:,-1].values
df = d1.iloc[: , 2:].values

In [5]:
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [6]:
#imputer = Imputer(missing_values = 'NaN', strategy = 'mean')
#imputer.fit(X)

In [7]:
labelencoder_x1 = LabelEncoder()
X[:,1] =labelencoder_x1.fit_transform(X[:,1])
X[:,0] =labelencoder_x1.fit_transform(X[:,0])
X[:,2] =labelencoder_x1.fit_transform(X[:,2]) 
onehotencoder = OneHotEncoder(categorical_features=[1]) #
X= onehotencoder.fit_transform(X).toarray()


/home/vijay/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/vijay/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)# random_state=42

In [9]:
y_train

array([3, 2, 3, 2, 3, 1, 3, 2, 2, 2, 1, 3, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2,
       2, 2, 1, 3, 3, 1, 3, 2, 2, 1, 2, 1, 2, 2, 1, 3, 3, 3, 3, 3, 2, 3,
       1, 3, 1, 2])

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
knn.score(x_test, y_test)

0.9230769230769231

# Kmeans clustering

In [12]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler


In [34]:
kmeans = KMeans(n_clusters=3, max_iter=300, algorithm = 'auto')
kmeans.fit(X)


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [35]:
correct = 0
for i in range(len(X)):
    predict_me = np.array(X[i].astype(float))
    predict_me = predict_me.reshape(-1, len(predict_me))
    prediction = kmeans.predict(predict_me)
    if prediction[0] == y[i]:
        correct += 1

print(correct/len(X))

0.32786885245901637


# SVM implementation

In [37]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(x_train, y_train)  


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [39]:
y_pred = svclassifier.predict(x_test)  
y_pred

array([1, 2, 3, 1, 1, 2, 1, 1, 3, 1, 3, 2, 2])

In [40]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[1 0 0]
 [5 2 0]
 [0 2 3]]
              precision    recall  f1-score   support

           1       0.17      1.00      0.29         1
           2       0.50      0.29      0.36         7
           3       1.00      0.60      0.75         5

   micro avg       0.46      0.46      0.46        13
   macro avg       0.56      0.63      0.47        13
weighted avg       0.67      0.46      0.51        13



# used cosine silimarity for better recommendation

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df)
print (tfidf_matrix.shape)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)
array([[ 1.        ,  0.36651513,  0.52305744,  0.13448867]])
    

AttributeError: 'numpy.ndarray' object has no attribute 'lower'